theme: jekyll-theme-time-machine
title: Сайт-портфолио студентки 2 курса Васильевой Марины
description: РГПУ им.Герцена, ИВТ, группа 1.1
show_downloads: true
github:
  zip_url: https://vk.com/marishavasilyeva
